### ISSUE TITLE
Liczba pierwsza

### ISSUE THREAD

**Issue by ghost** [neojski/js-introduction#10]
Zadanie polegałoby na napisaniu funkcji prime(n), której celem jest sprawdzenie czy dany argument jest nieujemną liczbą całkowitą pierwszą - w tym wypadku powinna zwrócić string "YES", w przeciwnym razie string "NO".

**Comment by neojski** [comment]
Niech będzie. Choć np. zastanów się nad wymaganiem, żeby zwracać: `{left: największa liczba pierwsza mniejsza (<) od n, right: najmniejsza liczba pierwsza większa (<) od n}`. Choć nie nalegam.

**Comment by ghost** [comment]
Dobrze, w takim razie należy zwrócić tablicę dwóch stringów proponowaną przez Tomka, jeśli któraś z odpowiednich liczb nie występuje należy zwrócić zamiast niej -1.
Np:
dla n = 5 mamy {left: 3, right: 7}
dla n = jakis_string mamy {left: -1, right: -1}

**Comment by neojski** [comment]
Super, to postaraj się ten opis zamieścić w instruction taska.
