### ISSUE TITLE
Suma 0

### ISSUE THREAD

**Issue by karolb** [neojski/js-introduction#11]
Napisać funkcję isZero() która sprawdzi czy w tablicy istnieją dwa elementy sumujące się do zera. Jeżeli istnieje to wypisz "TAK" jeżeli nie posiadają się takie elementy to wypisze "NIE".

**Comment by neojski** [comment]
Trochę zbyt proste. Niech znajduje pary liczb, które sumują się do 0 i usunie je z tablicy. Tzn.

```
var a = [1, 4, 5, 1 2, -1, 0, -2]
f(a) // zwraca tablicę [4, 5, 1, 0]
```

Przy czym musisz jakoś zdefiniować co się dzieje jak jest więcej kandydatów do wyrzucenia.

**Comment by karolb** [comment]
Może, żeby wyliczyć jakiś iloczyn tych, które zostaną?

**Comment by neojski** [comment]
Jeśli Cię to nie zadowala to zwracaj dwie tablice: elementy wycięte i elementy pozostałe. (np. jako obiekt: `{zero: [4, 5, 1, 0], rest: [1, -1, 2, -2]}`, czy coś w tym guście. Szczegóły należą do Ciebie.

**Comment by neojski** [comment]
Zamykam. #11
