### ISSUE TITLE
Discrete knapsack problem

### ISSUE THREAD

**Issue by jakubbrzeski** [neojski/js-introduction#14]
Na wejściu dane są kolejno 
n - liczba przedmiotów, W - pojemność plecaka
{w}_n - ciąg wag/wielkości/objętości przedmiotów
{c}_n - ciąg kosztów przedmiotów 

Należy wypisać jaki jest maksymalny sumaryczny koszt przedmiotów które możemy zabrać, tak aby suma ich wag nie przekroczyła pojemności plecaka.

**Comment by neojski** [comment]
Szczerze mówiąc wolałbym zadanie bardziej strukturowe js niż algorytmiczne, ale niech będzie.
