### ISSUE TITLE
Fabryka

### ISSUE THREAD

**Issue by ghost** [neojski/js-introduction#15]
Zadanie polega na zasymulowaniu procesu produkcji w fabryce liczb "Cyferka".
Należy napisać funkcję produce, przyjmującą dwie tablice liczb - elementy konstrukcyjne oraz instrukcje. Funkcja produce ma zbierać (aż się skończą) po dwie liczby z tablicy instrukcji: działanie i liczba argumentów. Wśród działań znajdują się np. dodawanie (modulo ostatnia liczba), mnożenie (modulo ostatnia liczba), coś 'a la' iloczyn skalarny dla wektorów utworzonych z pierwszej i drugiej połowy argumentów, średnia arytmetyczna. Tablica elementów konstrukcyjnych może zawierać defekty (np. puste stringi), które trzeba pominąć i brać kolejny argument (ew. zwrócić string z błędem). Wszystkie wyniki należy wpisywać do wynikowej talicy, która będzie zwracana na końcu programu.

**Comment by neojski** [comment]
Ok, byle nie przesadzaj ze złożonością tego zadania.
