### ISSUE TITLE
Sortowanie po ilości znaków

### ISSUE THREAD

**Issue by mkowalik** [neojski/js-introduction#35]
Napisz funkcję f(array), która przyjmuje jeden argument - tablicę stringów i posortuje jej elementy po pierwsze po ilości znaków, po drugie zgodnie z ich kolejnością jak tablicy array w argumencie (sortowanie stabilne po ilości znaków) i zwróci tablicę tych elementów w zadanej kolejności. Do sortowania należy wykorzystać metodę array.sort(sortfunction).

**Comment by neojski** [comment]
Sortowanie spoko, ale osobiście nie rozumiem treści, tzn. co znaczy posortować "'zgodnie z kolejnością na liście argumentów". Ale podejrzewam, że po uściśleniu będzie ok.

**Comment by mkowalik** [comment]
Tak, tam jest maly błąd, bo na początku funkcja miała mieć nieokreśloną
liczbę argumentów, ale to olałem i zmieniłem argument po prostu na tablicę,
no i zostało niepoprawione... Zaraz naprawię i będzie ok :-)
7 wrz 2013 18:43, "Tomasz Kołodziejski" notifications@github.com
napisał(a):

**Comment by neojski** [comment]
Czyli mam rozumieć, że posortować stabilnie wg długości stringa, tak? Jeśli tak, to warto też dodać ten opis, bo jest krótki i zrozumiały.

**Comment by mkowalik** [comment]
Tak, w sumie tak :-)
7 wrz 2013 22:48, "Tomasz Ko³odziejski" notifications@github.com
napisa³(a):

**Comment by neojski** [comment]
Zmergowałem w https://github.com/neojski/js-introduction/commit/67db687e9092519012dc21b07f0c8cc9230537ac. Po drodze zmieniłem commit message żeby był taki, jak inne, tzn. `(#35) - custom string-sorting`.

Ponieważ zadanie domowe już nie obowiązuje, pozwolę sobie na komentarz:
Bardzo mi się podoba jak moje pierwsze rozwiązanie

``` js
var f = function(array){
    return array.sort(function(a, b) {
        return a.length !== b.length ? a.length - b.length : array.indexOf(a) - array.indexOf(b); 
    });
};
```

nie przechodzi ostatniego testu. Szybka poprawka dała:

``` js
var f = function(array){
    return array.map(function(x, i) {
        return [x, i];
    }).sort(function(a, b) {
        return a[0].length !== b[0].length ? a[0].length - b[0].length : a[1] - b[1]; 
    }).map(function(x){
        return x[0];
    });
};
```

Choć chętnie zobaczę czy miałeś lepszy pomysł na rozwiązanie.

**Comment by mkowalik** [comment]
Po prostu:

var f = function(array){
    array.sort(function(a, b){
return a.length - b.length;
});
 return array;
};

W dniu 8 wrze¶nia 2013 14:56 u¿ytkownik Tomasz Ko³odziejski <
notifications@github.com> napisa³:

> Zmergowa³em w 67db687https://github.com/neojski/js-introduction/commit/67db687e9092519012dc21b07f0c8cc9230537ac.
> Po drodze zmieni³em commit message ¿eby by³ taki, jak inne, tzn. (#35) -
> custom string-sorting.
> 
> Poniewa¿ zadanie domowe ju¿ nie obowi±zuje, pozwolê sobie na komentarz:
> Bardzo mi siê podoba jak moje pierwsze rozwi±zanie
> 
> var f = function(array){
>     return array.sort(function(a, b) {
>         return a.length !== b.length ? a.length - b.length : array.indexOf(a) - array.indexOf(b);
>     });};
> 
> nie przechodzi ostatniego testu. Szybka poprawka da³a:
> 
> var f = function(array){
>     return array.map(function(x, i) {
>         return [x, i];
>     }).sort(function(a, b) {
>         return a[0].length !== b[0].length ? a[0].length - b[0].length : a[1] - b[1];
>     }).map(function(x){
>         return x[0];
>     });};
> 
> Choæ chêtnie zobaczê czy mia³e¶ lepszy pomys³ na rozwi±zanie.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/neojski/js-introduction/issues/35#issuecomment-24020415
> .

## 

Pozdrawiam,
Micha³ Kowalik

**Comment by neojski** [comment]
Więc działa przypadkowo, to znaczy wg [dokumentacji](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.11):

> The elements of this array are sorted. The sort is not necessarily stable (that is, elements that compare equal do not necessarily remain in their original order)
> Choć pewno trafiłeś na przeglądarkę, która [akurat ma](http://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers) stabilną wersję sortowania.

**Comment by mkowalik** [comment]
Hmm... To zdecydowanie nie doczyta³em :-/
8 wrz 2013 18:42, "Tomasz Ko³odziejski" notifications@github.com
napisa³(a):
