### ISSUE TITLE
Sortowanie po ilości znaków

### ISSUE THREAD

**Issue by mkowalik** [neojski/js-introduction#36]
Napisz funkcję f(array), która przyjmuje jeden argument - tablicę stringów i posortuje jej elementy po pierwsze po ilości znaków, po drugie zgodnie z kolejnością na liście argumentów i zwróci tablicę tych elementów w zadanej kolejności. Do sortowania należy wykorzystać metodę array.sort(sortfunction).

**Comment by neojski** [comment]
Duplikat #35.
