### ISSUE TITLE
Suma liczb nieparzystych w danej tablicy

### ISSUE THREAD

**Issue by ghost** [neojski/js-introduction#5]
Proponuję task polegający na napisaniu funkcji sumującej te liczby w zadanej tablicy które są nieparzyste.

**Comment by neojski** [comment]
Świetnie. Proponuję dwie poprawki:
1. sum_of_odd_numbers -> sum-of-odd-numbers (tak jak w innych plikach)
2. zmiana nazwy pliku z ex3 na jakąś rozsądniejszą (sum-of-odd-numbers)
3. malutkie utrudnienie (bo samo zadanie mogłoby być zbyt jednak proste): niech dzieje się rekurencyjnine, tj. jeśli element tablicy jest tablicą, to niech sprawdzi się rekurencyjnie: `f([[1, 4, 2], [-1, 6, 8, 3, [-3, 4, 0, -4, 5]], -5, -8]) === 0`
4. ewentualnie niech `f` działa dla zmiennej liczby argumentów

Po tych zmianach proponuję poprawić PR i mergujemy. (spróbuj tak, żeby był tylko jeden commit) Sugeruję też zmianę commit messagu na jakiś bardziej opisowy: `impementation of sum-of-odd-numbers task`

Aha, poprawiłem też opis na giście, bo bardzo dobrze na githubie sprawdza się opis PR pt. "(#nr issue) opis". Wtedy w tym issue wyświetli się referencja do Twojego PR. Jak będziesz zmieniać na bardziej opisowy, użyj proszę tej składni.

**Comment by ghost** [comment]
Co dla ciebie oznacza PR? Bo dla mnie https://en.wikipedia.org/wiki/Public_relations

**Comment by neojski** [comment]
Miałem na myśli Pull Request.
