### ISSUE TITLE
Wyznaczanie n-tej z kolei liczby fibonacciego modulo pewne p

### ISSUE THREAD

**Issue by sokar92** [neojski/js-introduction#7]

**Comment by neojski** [comment]
Przypuszczam, że to zadanie może być bardziej algorytmiczne niż js. (w szczególności na przykład działania bitowe, bo przypuszczam, że chcemy szybkie potęgowanie macierzy, są wolne w js)

Proponuję, np. żeby wykorzystać funkcję filter, map czy reduce, jakąś wariację, pt. zwróć tablicę kwadratów pierwszych n liczb Fibonacciego (począwszy od 0 1) począwszy od największego.

**Comment by sokar92** [comment]
Wersja bardzo prosta  mozna ja rozwiazac liniowo  test pierwszych wartosci tylko

**Comment by neojski** [comment]
Kilka uwag:
1. wcięcia: https://github.com/neojski/js-introduction/pull/8/files (wygląda to koszmarnie, tj. mieszanie tabów i spacji)
2. Twoje testy zawierają kompletne rozwiązanie, które wystarczy w zasadzie przekleić...
3. warto napisać, że oczekujesz wyrazów kolejno: 0, 1, 1, 2, 3, 5, 8, ... dla argumentów od 0, tj. tj. f0=0, f1=1, f2=1, itd.
4. w zasadzie to liczenie modulo jest dość nonsensowne i będzie utrudniało ludziom debug. Wywaliłbym to modulo chyba całkiem. Np. każ zwracać tablicę (czy obiekt) taki: `{fn: n-ta liczba fibonacciego, sum: suma n pierwszych liczb fibonacciego}`. Lub jeśli chcesz modulo, to jeszcze dorzucić do tego obiektu `{mul: iloczyn n-liczb modulo n}`.
