### ISSUE TITLE
Wyrażenia regularne

### ISSUE THREAD

**Issue by Ziemin** [neojski/js-introduction#9]
Należy wyszukać imiona i nazwiska w tekście składającym się z dowolnych znaków - każde imię oraz nazwisko zaczyna się dużą literą, otoczone jest spacjami oraz składa się tylko z liter alfabetu angielskiego. Następnie trzeba takie pary posortować i oraz odwrócić w nich kolejność znaków.

**Comment by neojski** [comment]
+1
